### ISSUE TITLE
Identify how to encode which tests should be run on which resources

### ISSUE THREAD

**Issue by putmantime** [TranslatorSRI/SRI_testing#13]
Some tests are intended for nodes that are part of ontologies.  If a subject is a gene, and the test is trying to find its parent it will and should fail. But if the subject is a chebi ontology term, it should have a parent and would be expected to pass.
We need to come up with a method to identify what subset of tests should be run for a given resource.

Note:
We could keep a list of namespaces appropriate for each use case to check against.

**Comment by RichardBruskiewich** [comment]
Granularity of this constraint may be at two levels: the whole KP or ARA, or just at the level of one particular test. 

In some cases, a given test failure may be specific to a particular identifier used (i.e. as subject or object) but not to the namespace per say?

Since there is likely a finite set of actual tests to be applied against each data template, perhaps each such test could be assigned a shorthand code or number (concise and easy to programmatically use; not so human readable though?).

Then, we can add an optional JSON tag, something like `exclude` or `exclude_test` with the array of shorthand codes or numbers of tests to be excluded. 

This tag could be at the top level file level (to exclude a given test from all data entries in the file) or just at the level of a particular test(?), overriding the global settings (whatever it is).

**Comment by RichardBruskiewich** [comment]
Resolved by PR#21
